"""SQLAlchemy database models and setup."""

from datetime import datetime
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


class Conversation(db.Model):
    """Represents a chat conversation/session."""
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    summary = db.Column(db.Text)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    last_updated = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    # Rolling summary fields for auto-summarization
    rolling_summary = db.Column(db.Text, default='')
    messages_summarized = db.Column(db.Integer, default=0)
    last_summary_at = db.Column(db.DateTime, nullable=True)
    messages = db.relationship('Message', backref='conversation', lazy=True, cascade='all, delete-orphan')


class Message(db.Model):
    """Represents a single message in a conversation."""
    id = db.Column(db.Integer, primary_key=True)
    conversation_id = db.Column(db.Integer, db.ForeignKey('conversation.id'), nullable=True)
    role = db.Column(db.String(20), nullable=False)  # 'user' or 'assistant'
    content = db.Column(db.Text, nullable=False)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)


class MemoryMarker(db.Model):
    """Represents a compression checkpoint where older messages are summarized."""
    id = db.Column(db.Integer, primary_key=True)
    conversation_id = db.Column(db.Integer, db.ForeignKey('conversation.id'), nullable=False)
    summary_text = db.Column(db.Text, nullable=False)
    covers_before = db.Column(db.DateTime, nullable=False)  # Messages before this timestamp are summarized
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    messages_compressed = db.Column(db.Integer, default=0)
    tokens_saved = db.Column(db.Integer, default=0)

    conversation = db.relationship('Conversation', backref=db.backref('memory_markers', lazy=True, cascade='all, delete-orphan'))


class UserProfile(db.Model):
    """Stores persistent user details for AI context."""
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), default='')
    details = db.Column(db.Text, default='')  # Max 125 words enforced in frontend
    updated_at = db.Column(db.DateTime, default=datetime.utcnow)


class TokenUsage(db.Model):
    """Tracks token usage per AI response."""
    id = db.Column(db.Integer, primary_key=True)
    conversation_id = db.Column(db.Integer, db.ForeignKey('conversation.id'), nullable=True)
    tokens_output = db.Column(db.Integer, default=0)  # Tokens generated by AI
    tokens_per_second = db.Column(db.Float, default=0)  # Speed of generation
    duration_ms = db.Column(db.Integer, default=0)  # Time taken in milliseconds
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)


class ThreadView(db.Model):
    """Stores thread/view state for multi-user or multi-view support."""
    thread_id = db.Column(db.String(36), primary_key=True)
    user_id = db.Column(db.String(100), nullable=False)
    content = db.Column(db.JSON)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow)


def init_db(app):
    """Initialize database with Flask app."""
    db.init_app(app)
    with app.app_context():
        db.create_all()
